name: potato
description: Your translation companion for flutter apps.

publish_to: "none" # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  file_picker: ^5.3.0
  fluent_ui: ^4.6.0
  flutter:
    sdk: flutter

  flutter_riverpod: ^2.3.6
  http: ^0.13.6
  linked_scroll_controller: ^0.2.0
  logger: ^1.3.0
  path: ^1.8.2
  path_provider: ^2.0.15
  shared_preferences: ^2.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  mocktail: 0.3.0

flutter:
  uses-material-design: true
