name: potato
description: Your translation companion for flutter apps.

publish_to: "none" # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  file_picker: ^5.2.0+1
  fluent_ui: ^4.0.0
  flutter:
    sdk: flutter

  flutter_riverpod: ^2.0.0-dev.9
  http: ^0.13.5
  linked_scroll_controller: ^0.2.0
  logger: ^1.1.0
  path: ^1.8.2
  path_provider: ^2.0.9
  shared_preferences: ^2.0.15

dev_dependencies:
  flutter_test:
    sdk: flutter
  lint: ^1.10.0
  mocktail: 0.3.0

flutter:
  uses-material-design: true
