name: potato
description: Your translation companion for flutter apps.

publish_to: "none" # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ">=2.16.0 <3.0.0"

dependencies:
  file_picker: ^4.5.1
  fluent_ui: ^3.9.1
  flutter:
    sdk: flutter

  flutter_riverpod: ^1.0.3
  logger: ^1.1.0
  path_provider: ^2.0.9

dev_dependencies:
  flutter_lints: ^1.0.0
  flutter_test:
    sdk: flutter
  lint: ^1.0.0
  mocktail: 0.3.0

flutter:
  uses-material-design: true
